name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    environment: github-actions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: "Install uv"
      uses: astral-sh/setup-uv@v7

    - name: "Install project (uv)"
      shell: bash
      run: |
        uv sync --all-extras --dev

    - name: Static checks
      shell: bash
      run: |
        uv run black --check dagviz
        uv run mypy dagviz
        uv run flake8 dagviz

    - name: Build package
      shell: bash
      run: |
        uv build
        echo "release-file=$(cd dist && echo *.gz)" >> $GITHUB_OUTPUT

    - name: Test
      shell: bash
      run: |
        uv run pytest --cov dagviz --cov-branch --cov-report xml

    - name: Build docs
      shell: bash
      run: |
        uv run pdoc -f --html -o docs dagviz --template-dir doc-template
        mkdir -p docs/notebooks
        cp notebooks/*.html docs/notebooks

    - name: Deploy docs
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs
        jekyll: false
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}