name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    environment: github-actions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: "Install poetry"
      shell: bash
      run: |
        pip install -U pip
        pip install poetry

    - name: "Set-up virtual env"
      shell: bash
      run: |
        export long_version=$(git describe --tags --abbrev=12)
        export short_version=$(git describe --tags --abbrev=0)
        # Make version pep0440 compliant
        export pkg_version=${long_version/$short_version-/$short_version+}
        poetry config virtualenvs.create false
        poetry version ${pkg_version#v}
        poetry install --no-root

    - name: Static checks
      shell: bash
      run: |
        black --check dagviz
        mypy dagviz
        flake8 dagviz

    - name: Build docs
      shell: bash
      run: |
        git worktree add docs gh-pages
        pdoc -f --html -o docs dagviz
        rm -rf docs/notebooks
        mkdir -p docs/notebooks
        cp notebooks/*.html docs/notebooks

    - name: Build package
      shell: bash
      run: |
        poetry build
        poetry install
        echo "::set-output name=release-file::$(cd dist && echo *.gz)"

    - name: Test
      shell: bash
      run: |
        pytest --cov dagviz --cov-branch --cov-report xml

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
