from typing import Any, Tuple
from .container import Group

class Drawing:
    def tostring(self) -> str: ...
    def viewbox(self, x: float, y: float, w: float, h: float) -> None: ...
    def g(self) -> Group: ...
    def add(self, element: Any) -> None: ...
    def path(self, d: str, **kwargs: Any) -> Any: ...
    def circle(self, xy: Tuple[float, float], radius: float, **kwargs: Any) -> Any: ...
    def line(
        self, a: Tuple[float, float], b: Tuple[float, float], **kwargs: Any
    ) -> Any: ...
    def text(self, text: str, xy: Tuple[float, float], **kwargs: Any) -> Any: ...
